/** Plain language explanations of the validation codes the backend can report. */
export const ISSUE_HELP: Record<string, { meaning: string; outcome: "Row rejected" | "Row kept" }> = {
  MISSING_STUDENT_ID: { meaning: "The student id is blank.", outcome: "Row rejected" },
  MISSING_SCHOOL: { meaning: "The school name is blank.", outcome: "Row rejected" },
  INVALID_GRADE: { meaning: "Grade is not a whole number.", outcome: "Row rejected" },
  GRADE_OUT_OF_RANGE: { meaning: "Grade is outside 0 to 12.", outcome: "Row rejected" },
  INVALID_YEAR: { meaning: "Academic year is not a four digit year.", outcome: "Row rejected" },
  INVALID_TERM: { meaning: "Term is not FALL or SPRING.", outcome: "Row rejected" },
  INVALID_ECONOMIC_STATUS: { meaning: "Economic status is not LOW_INCOME or NOT_LOW_INCOME.", outcome: "Row rejected" },
  INVALID_ENGLISH_LEARNER: { meaning: "English learner is not Y or N.", outcome: "Row rejected" },
  INVALID_SCORE: { meaning: "A score is not a number.", outcome: "Row rejected" },
  SCORE_OUT_OF_RANGE: { meaning: "A score is outside 0 to 100.", outcome: "Row rejected" },
  INVALID_ATTENDANCE: { meaning: "Attendance is not a number.", outcome: "Row rejected" },
  ATTENDANCE_OUT_OF_RANGE: { meaning: "Attendance is outside 0 to 1 (or 0 to 100 as a percent).", outcome: "Row rejected" },
  INVALID_DISCIPLINE: { meaning: "Incident count is not a whole number of 0 or more.", outcome: "Row rejected" },
  MALFORMED_ROW: { meaning: "The row has a different number of columns than the header.", outcome: "Row rejected" },
  DUPLICATE_ROW: { meaning: "The same student and term appears earlier in this file.", outcome: "Row rejected" },
  DUPLICATE_EXISTING: { meaning: "This student and term is already stored. Use replace mode to load a corrected file.", outcome: "Row rejected" },
  MISSING_MATH_SCORE: { meaning: "Math score is blank. It was left empty.", outcome: "Row kept" },
  MISSING_READING_SCORE: { meaning: "Reading score is blank. It was left empty.", outcome: "Row kept" },
  MISSING_ATTENDANCE: { meaning: "Attendance is blank. It was left empty.", outcome: "Row kept" },
  MISSING_DISCIPLINE: { meaning: "Incident count is blank. It was counted as 0.", outcome: "Row kept" },
  ATTENDANCE_PERCENT_NORMALIZED: { meaning: "Attendance looked like a percent, so it was divided by 100.", outcome: "Row kept" },
};
